### ISSUE TITLE
Host and port

### ISSUE THREAD

**Issue by noraj** [glitchedgitz/grroxy-issues#18]
Having 2 instances at the same time is not possible right now.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/16578570/e98db58b-63f6-4bba-a621-b46d04bc5b7e)

Launching a second instance:

- It fails with `Error: unknown command "create" for "grroxy-linux"` instead of saying that the host:port is already in use, that's very weird
- It would be nice to have an option specify the host and port for the webUI, so one could host that on something else than localhost have a way around is the port is already taken, so adding `--ui-host` and `--ui-port options`
- Same but for the proxy (8888), `--proxy-host` and `--proxy-port options`
- Same but for what whatever is running on 127.0.0.1:10080, SOCKS proxy?

The options should not be only available for the create command but also for the list command when resuming an existing project.

**Comment by noraj** [comment]
NOte: I'm not sure why the ASCII art displays two times.

**Comment by noraj** [comment]
> In future, if port is in use, it will auto choose empty ports and connect.

I was going to suggest that later but yeah it would be sugar in case of conflict.

**Comment by glitchedgitz** [comment]
Done in version `v0.15.6`
- `--host` for hosting main app
- `--proxy` for proxy address
- Auto select next port if supplied port is in use.
