### ISSUE TITLE
[BUG] - Character ":" at the end of the domain - Repeater

### ISSUE THREAD

**Issue by QU35T-code** [glitchedgitz/grroxy-issues#2]
When a request is sent to the repeater, a **":"** character is added to the end of the domain.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/20f1bbf9-31c9-4ad6-bdbb-d390d296577b)

This character can lead to **confusion**, although I think you put it here so that we know we can add a custom port if we need to. I don't think the ":" is useful and it makes sense to add it if we need it.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/051f9bf9-8e4e-4618-9857-bf0dddb09cb1)

**Comment by glitchedgitz** [comment]
Not intentional, it's a bug 
![image](https://github.com/glitchedgitz/grroxy-issues/assets/58145476/3ee42628-3f3e-4ef3-aed8-1be2ca359b27)

**Comment by glitchedgitz** [comment]
Fixed
