### ISSUE TITLE
drop and forward buttons on history tab

### ISSUE THREAD

**Issue by noraj** [glitchedgitz/grroxy-issues#20]
I think the drop and forward buttons shouldn't be displayed on the history tab but only for the intercept tab.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/16578570/573ec717-a805-4987-9a6c-75998bdafa15)

**Comment by glitchedgitz** [comment]
Yes

**Comment by glitchedgitz** [comment]
Done
