### ISSUE TITLE
Intruder - void contextual menu

### ISSUE THREAD

**Issue by noraj** [glitchedgitz/grroxy-issues#25]
On repeater, the contextual menu is working but on intruder it's empty

![image](https://github.com/glitchedgitz/grroxy-issues/assets/16578570/1b4bb212-e4fd-45fb-9294-6ecd1e07b770)

**Comment by glitchedgitz** [comment]
Already reported on #12

**Comment by noraj** [comment]
Sorry for the duplicate.
