### ISSUE TITLE
[FEATURE] - Closing tabs

### ISSUE THREAD

**Issue by QU35T-code** [glitchedgitz/grroxy-issues#3]
I can't see how to close the tabs in the playground. There's no button to easily close them.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/343955e0-b1bc-44b4-9759-eef436c3b0e9)

**Comment by glitchedgitz** [comment]
I have a different plan regarding playground & working. Let me prepare the mockups and we will discuss this in discord.

**Comment by glitchedgitz** [comment]
This will be completed with the #23
