### ISSUE TITLE
[BUG][UI/UX] - Drop-down menu does not close when clicked

### ISSUE THREAD

**Issue by QU35T-code** [glitchedgitz/grroxy-issues#4]
When clicking on the "**Rename", "Duplicate All", "Duplicate Content"** tabs, the drop-down menu remains open, which isn't very UX-friendly.
It should **close** when one of these tabs is clicked, as it does when the "delete" button is clicked.

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/f262ffb9-37fd-4378-9b8d-94171d742d1f)

**Comment by glitchedgitz** [comment]
Fixed!
