### ISSUE TITLE
[BUG / Question] - Wordlists not found

### ISSUE THREAD

**Issue by QU35T-code** [glitchedgitz/grroxy-issues#5]
When I search for the Seclists wordlists raft-small-words.txt(https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/raft-small-words.txt), I get no results. Should I install Seclists on my machine? If so, in which folder?

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/89db5cb7-985b-4941-b413-8395dbd19a76)

Also, all the web buttons add the same wordlists widget, so I think it's best to leave only wordlists in the menu, don't you? 

![image](https://github.com/glitchedgitz/grroxy-issues/assets/51704860/948866b7-c0d7-491d-b427-54bd14c503ea)

**Comment by glitchedgitz** [comment]
I have to add the suggestions, currently you can use `cook search api` from there just put the keyword and it will work.

**Comment by glitchedgitz** [comment]
> Also, all the web buttons add the same wordlists widget, so I think it's best to leave only wordlists in the menu, don't you?

I agree, same thing for cases as well.

**Comment by glitchedgitz** [comment]
Fixed in v0.16.0
